### ISSUE TITLE
Kubernetes ingress subpaths don't work with tabix

### ISSUE THREAD

**Issue by DrissiReda** [tabixio/tabix#211]
I tried using tabix inside a kubernetes cluster. 

I need tabix to work in a subpath so : host.name.somewhere/tabix

But whenever tabix needs access to its assets it searches for them on `host.name.somewhere/styles` instead of `host.name.somewhere/tabix/styles`

My ingress:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: tabix
  namespace: somespace
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tabix
          servicePort: 8125
        path: /
```

what am I missing?
